### ISSUE TITLE
What is the differance between this image and the self-hosted image?

### ISSUE THREAD

**Issue by BobWs** [standardnotes/server#335]
As the title says what is the difference between this image and the self-hosted one? There is not clear documentation about all the changes in images and containers for self-host enthusiastic! 

Everytime there is a new name for a image/container and no clear instructions what has changed and which one to use.

**Comment by 0x111** [comment]
What do you mean this image? The self-hosted branch contains a compose file and env variables for the various services needed to run standardnotes.  This repository contains multiple distinct, although related projects. 
So instead of having separate repositories for auth server, files server etc. this repository contains all of the services under the packages folder.

Does this answer you question?

**Comment by BobWs** [comment]
> Does this answer you question?

Okay thanks for answering! So as I understand there is only on container to install? Is there a docker-compose file for this? The one I have found is only with the database and redis.
TIA

**Comment by 0x111** [comment]
You can find all the instructions you might need here https://github.com/standardnotes/self-hosted
