### ISSUE TITLE
Manually decrypt file uploads with secret

### ISSUE THREAD

**Issue by AdamXweb** [standardnotes/server#921]
Long story short, my migration to V2 wasn't a success, so figured i'd export a backup from the application and then import it into the new v2 instance.

Although this worked for the notes, the files didn't come across..

Could I please get some assistance in manually decrypting the files from my old instance with a secret?

Thanks!

**Comment by moughxyz** [comment]
File decryption would have nothing to do with the server based secrets. They are encrypted with your client-based account keys. So as long as you place the encrypted files in the right place on the server side so that the client can pick them up, you should be good to go.

As for where they should be located, you can try uploading a new file to see where it gets placed in your new server directory.

**Comment by AdamXweb** [comment]
It looks like because the new installation was done from scratch, copying the files in the upload folder across didn't work. Any suggestions?

**Comment by moughxyz** [comment]
You'll have to be more specific about what didn't work, and what errors you're seeing.

Do newly uploaded files work?

**Comment by AdamXweb** [comment]
New files upload to the v2 server fine, however the encrypted files from v1 that has different environment keys don't load if copied into the v2 uploads folder.

Would it be possible to perform the decryption on these files with one of the keys or password in a way like the [decrypt](https://github.com/standardnotes/decrypt) tool?

Sorry, this may not be the right place to raise this issue.

**Comment by AdamXweb** [comment]
I receive a 400 bad request when trying to load an image
Interestingly I changed the file permissions and they worked! Closing the issue
